### ISSUE TITLE
Spits out error repeatedly 

### ISSUE THREAD

**Issue by I2pRandom** [NodeMixaholic/cryptoxmr-automator#1]
The script spits out an "errors. (did you exit out of the page?)" 
![image](https://user-images.githubusercontent.com/42506001/212461839-9a5198b4-2de5-4107-89a0-3d1df104ab48.png)

I had to remove the headless: true to make the script work, the script doesn't open an instance of chrome on my vnc desktop, idk if it's because i had to remove the headless: true

**Comment by NodeMixaholic** [comment]
This is normal behavior and should be expected. However, I should really tell people that in the README...
